pharo-vcs/iceberg

Iceberg.package/IceCloneRepositoryModel.class/instance/changeLocation.st
`#chooseDirectory:`'s argument is the window title, not the location.
=> Fixes #95 - Use #chooseDirectoryFrom:  to preselect the location, and not pick the title.

README.md
Replace download from branch 'stable' to default 'master' branch. Otherwise people will load old versions.
=> Fix branch in download script

Iceberg.package/IceCloneRepositoryModel.class/instance/initializeWidgets.st
Change clone URL in dialog from 'git@github.com:' into 'git@github.com:user/project.git'
so the dialog is easy to fill out/the format is easier to remember
=> Change clone URL so it is easy to remember

.travis.yml
* removed Pharo-5 (which Iceberg doesn't support)
* Changed Pharo-6 to Pharo-alpha, because stable VM doesn't support
iceberg's git
second attempt, based from dev-0.5 branch (although it shouldn't make a difference)
=> * commented-out ssh-key loading (it wasn't used)

Iceberg.package/IceNetworkRemote.class/instance/userName.st
The method
IceNetworkRemote>>userName
^user ifNil: [ String empty ] ifNotNil: ''.
should be
IceNetworkRemote>>userName
^user ifNil: [ String empty ] ifNotNil: [ user ].
=> Correct IceNetworkRemote>>userName

Iceberg-UI.package/IceCommitModel.class/instance/contractedNameFor..st, Iceberg-UI.package/IceCommitModel.class/instance/initialize.st
I propose to contract the name of the branches if it is too long. 
I choose 20 characters but this is just a proposition. Maybe another length will be better. I'm open to suggestion. (Or maybe others won't even judge the contraction useful)
=> Contract the name of a branch to 20 characters for buttons

Iceberg.package/IceHttpRemote.class/instance/parseUrl.st
minor fix to http URL parsing that allows '.' to be part of the last path segment
=> URL parsing fix

Iceberg-UI.package/IceRepositoriesBrowser.class/instance/composePackagesListIn..st
Add a filter to the package view. Probably usefull for projects like Pharo. 
Issue related: https://github.com/pharo-vcs/iceberg/issues/393
=> cf_addFilterToPackageView

Iceberg-UI.package/IceCreateRepositoryModel.class/instance/guessSubDirectory.st, Iceberg-UI.package/IceCreateRepositoryModel.class/instance/initializeWidgets.st, Iceberg-UI.package/IceLocationModel.class/instance/choose.st, Iceberg-UI.package/IceLocationModel.class/instance/onChoose..st, Iceberg-UI.package/IceLocationModel.class/instance/onChoose.st, Iceberg-UI.package/IceLocationModel.class/properties.json
See: https://github.com/pharo-vcs/iceberg/issues/421
=> Guess the subdirectory while importing a local repository.

Iceberg.package/IceRepository.class/instance/commitCherryPick.withMessage.andParents..st
use package specific collection to create patch for cherry pick to prevent method mixups.
Fixes #450
=> 450 cherry picking from multiple packages mixes up methods

Iceberg-Libgit.package/IceSemanticVersion.class/instance/^equals.st, Iceberg-Libgit.package/IceSemanticVersion.class/instance/^less.st, Iceberg-Libgit.package/IceSemanticVersion.class/instance/hash.st
Put hash, = and < into the same method category as Object
Necessary to get tests green in latest Pharo 7.0 image (ProperMethodCategorizationTest)
Details in https://pharo.fogbugz.com/f/cases/20401
=> 20401 Categorization - IceSemanticVersion should follow Object protocol

Iceberg-UI.package/IceAbstractModel.class/instance/isModified.st, Iceberg-UI.package/IceRepositoriesBrowser.class/class/sortingSettingsOn..st, Iceberg-UI.package/IceRepositoriesBrowser.class/class/sortingStrategy..st, Iceberg-UI.package/IceRepositoriesBrowser.class/class/sortingStrategy.st, Iceberg-UI.package/IceRepositoriesBrowser.class/class/toDisplayFirst..st, Iceberg-UI.package/IceRepositoriesBrowser.class/class/toDisplayFirst.st, Iceberg-UI.package/IceRepositoriesBrowser.class/class/toDisplayLast..st, Iceberg-UI.package/IceRepositoriesBrowser.class/class/toDisplayLast.st, Iceberg-UI.package/IceRepositoriesBrowser.class/instance/composePackagesListIn..st, Iceberg-UI.package/IceRepositoriesBrowser.class/instance/sortModifiedFirstAction.st, Iceberg-UI.package/IceRepositoriesBrowser.class/instance/sortModifiedLastAction.st, Iceberg-UI.package/IceRepositoriesBrowser.class/instance/sortModifiedWithOthersAction.st, Iceberg-UI.package/IceRepositoriesBrowser.class/instance/sortNotLoadedFirstAction.st, Iceberg-UI.package/IceRepositoriesBrowser.class/instance/sortNotLoadedLastAction.st, Iceberg-UI.package/IceRepositoriesBrowser.class/instance/sortNotLoadedWithOthersAction.st, Iceberg-UI.package/IceRepositoriesBrowser.class/instance/sortingStrategy.st, Iceberg-UI.package/IceRepositoriesBrowser.class/properties.json, Iceberg-UI.package/IceSortingStrategy.class/README.md, Iceberg-UI.package/IceSortingStrategy.class/class/possibleValues.st, Iceberg-UI.package/IceSortingStrategy.class/instance/first..st, Iceberg-UI.package/IceSortingStrategy.class/instance/first.st, Iceberg-UI.package/IceSortingStrategy.class/instance/initialize.st, Iceberg-UI.package/IceSortingStrategy.class/instance/last..st, Iceberg-UI.package/IceSortingStrategy.class/instance/last.st, Iceberg-UI.package/IceSortingStrategy.class/instance/selectMatching.from..st, Iceberg-UI.package/IceSortingStrategy.class/instance/sort..st, Iceberg-UI.package/IceSortingStrategy.class/instance/sortByName..st, Iceberg-UI.package/IceSortingStrategy.class/instance/withOthers..st, Iceberg-UI.package/IceSortingStrategy.class/properties.json
Sorting of packages:
- Sort the packages aphabetically
- Add a sorting strategy. The user can customise the sorting to show the modified/not loaded packages first/last. 
- This customisation can be done via the package tab of Iceberg or via settings
For now I set those defaults: 
- First: modified
- Last: not loaded
This is my personnal choice. If it is too personal I can change it :)
Issue related: https://github.com/pharo-vcs/iceberg/issues/434
=> cf_packageSorting

Iceberg-Libgit.package/IceLibgitCommitWalk.class/instance/fromBranch..st, Iceberg-Libgit.package/IceLibgitLocalRepository.class/instance/commitsInBranch.do..st, Iceberg-Libgit.package/IceLibgitLocalRepository.class/instance/lookupHead.st, Iceberg-Libgit.package/IceLibgitLocalRepository.class/instance/outgoingCommits.st
I use some semantics in branch names. E.g. fixes/proj-number or 
feature/feature-name.  Or shared projects use user/their-work so make
it work. Pass name instead of baseName to get the full branch (the
refs/heads/ will be removed by other code) and pass the indication of
local/remote down to libgit.
=> $/ in a branch name is common. Pass indication of isRemote down

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/baseline..st
I added a required on Iceberg-UI to ensure the loading.
This will also probably require a merge against master because master is currently broken in Pharo 6. 
Close https://github.com/pharo-vcs/iceberg/issues/477
=> Pharo 6 specific package was not loaded into Pharo 6. 

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/tonel..st
The version of Tonel should be fixed, if it is not the pharo bootstrap is unstable and irrepetible
=> Fixing version of Tonel

Iceberg.package/IceLoadedCode.class/instance/computeReferenceCommit.st
Move reference commit to head if no other commit between saved package commit and head commit changes a package. Fixes #508
=> Move reference commit to head if no other commit between saved package commit and head commit changes a package. 

Iceberg.package/IceLoadedCode.class/instance/computeReferenceCommit.st
Trying to do more in order to detect the best version. If there are more versions in the image we can still try to find the most actual one by looking at the anchestry. If the anchestry chain is consistent than we get the actual one
=> Even better detect of possible referenceCommit

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/projectClass.st
This support is present in Pharo 6.1 and 7.
It should allow to update Iceberg without removing its packages first.
Close: https://github.com/pharo-vcs/iceberg/issues/546
=> Use Matecallo Cypress support if available in the baseline.

Iceberg.package/IceLocalBranch.class/instance/outgoingCommitsTo..st, Iceberg.package/IceLocalBranch.class/instance/reducedOutgoingCommitsWhenNoRemote.st
When pushing a new branch it should show all the commits. As this can be a lot, we are showing 20.
Fixes #651
=> Pushing a new branch has empty commit list.

Iceberg-TipUI.package/IceTipPackageFilter.class/instance/matches..st, Iceberg-UI-Tests.package/IceTipPackageFilterTest.class/instance/testMatches.st, Iceberg-UI-Tests.package/IceTipPackageFilterTest.class/properties.json
When adding a package, if we filter the list, use #asLowercase on both package name and pattern from the user.
Fixes https://github.com/pharo-vcs/iceberg/issues/665
=> cf_correctAddPackagesFilter

Iceberg-TipUI.package/IceTipCommentPanel.class/instance/initializeWidgets.st, Iceberg-TipUI.package/IceTipCommitBrowser.class/instance/initializeWidgets.st
Instead of selecting the diff view first, select the commit text area.
Fixes: https://github.com/pharo-vcs/iceberg/issues/720
**/!\ Please read /!\\** 
Since the focus order was already defined I'm not 100% sure it should be like that. But I still think it makes sense to select the commit text area first. I would like the thoughts of the reviewers.
=> Change focus order of commit window

Iceberg-TipUI.package/IceTipFetchAllProjectCommand.class/instance/execute.st
When the user tries to fetch for all repositories ask confirmation since it car takes some time.
Fixes https://github.com/pharo-vcs/iceberg/issues/726
=> Ask confirmation on fetch all action

Iceberg-TipUI.package/IceTipBranchWithCommitStatusBarItem.class/instance/branchNameMorph.st, Iceberg-TipUI.package/IceTipBranchWithCommitStatusBarItem.class/instance/execute.st, Iceberg-TipUI.package/IceTipBranchWithCommitStatusBarItem.class/instance/model..st, Iceberg-TipUI.package/IceTipBranchWithCommitStatusBarItem.class/instance/model.st, Iceberg-TipUI.package/IceTipBranchWithCommitStatusBarItem.class/instance/mouseEnter..st, Iceberg-TipUI.package/IceTipBranchWithCommitStatusBarItem.class/instance/mouseLeave..st, Iceberg-TipUI.package/IceTipBranchWithCommitStatusBarItem.class/instance/newStatusBarItemOn..st, Iceberg-TipUI.package/IceTipBranchWithCommitStatusBarItem.class/instance/shortIdMorph.st, Iceberg-TipUI.package/IceTipBranchWithCommitStatusBarItem.class/properties.json, Iceberg-TipUI.package/IceTipCopyCommitishCommand.class/class/browserRepositoryListActivation.st, Iceberg-TipUI.package/IceTipCopyCommitishCommand.class/class/canBeExecutedInContext..st, Iceberg-TipUI.package/IceTipCopyCommitishCommand.class/class/defaultMenuIconName.st, Iceberg-TipUI.package/IceTipCopyCommitishCommand.class/class/defaultMenuItemName.st, Iceberg-TipUI.package/IceTipCopyCommitishCommand.class/instance/execute.st, Iceberg-TipUI.package/IceTipCopyCommitishCommand.class/instance/readParametersFromContext..st, Iceberg-TipUI.package/IceTipCopyCommitishCommand.class/properties.json, Iceberg-TipUI.package/IceTipRepositoriesBrowser.class/instance/initializeRepositoryList.st, Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/branchName.st, Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/branchNameWithCommitId.st, Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/commitId.st, Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/shortCommitId.st, Iceberg-TipUI.package/IceTipWorkingCopyBrowser.class/instance/initializeStatusBar.st, Iceberg-TipUI.package/IceTipWorkingCopyModel.class/instance/branchNameWithCommitId.st, Iceberg-TipUI.package/IceTipWorkingCopyModel.class/instance/commitId.st, Iceberg-TipUI.package/IceTipWorkingCopyModel.class/instance/shortCommitId.st
Adding the short commit ID to the package window.
Adding an option to copy the commit ID.
Adding behavior to copy the commit ID when clicking in it.
Fix #750
=> Showing and coping the Commit ID

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/commander..st
Now commapder is hosted under pharo-ide and there is new version 0.6.2
=> Upgrade to Commander 0.6.2

Iceberg-Tests.package/IceBasicRepositoryFixture.class/instance/ensureRemoteRepository.st, Iceberg-Tests.package/IceBasicRepositoryFixture.class/instance/setUp.st, Iceberg-Tests.package/IceBasicRepositoryFixture.class/instance/tearDown.st, Iceberg-Tests.package/IceCleanWorkingCopyFixture.class/instance/setUp.st, Iceberg-Tests.package/IceCleanWorkingCopyTest.class/properties.json, Iceberg-Tests.package/IceDetachedWorkingCopyFixture.class/instance/setUp.st, Iceberg-Tests.package/IceDirtyDetachedWorkingCopyFixture.class/instance/setUp.st, Iceberg-Tests.package/IceGitCleanWorkingCopyTest.class/properties.json, Iceberg-Tests.package/IceHttpsRemoteTest.class/instance/defaultTestClass.st, Iceberg-Tests.package/IceMissingLocalRepositoryFixture.class/instance/setUp.st, Iceberg-Tests.package/IceMultiplePackageFixture.class/instance/setUp.st, Iceberg-Tests.package/IceParameterizedTestCase.class/instance/cleanUpInstanceVariables.st, Iceberg-Tests.package/IceParameterizedTestCase.class/instance/setUp.st, Iceberg-Tests.package/IceParameterizedTestCase.class/instance/tearDown.st, Iceberg-Tests.package/IceSinglePackageFixture.class/instance/setUp.st, Iceberg-Tests.package/IceSinglePackageLocalRepositoryTest.class/instance/testListBranchesListsExistingBranches.st, Iceberg-Tests.package/IceTestCase.class/instance/testListBranchesListsExistingBranches.st, Iceberg-Tests.package/IceTestCase.class/instance/testListBranchesListsNewBranch.st, Iceberg-Tests.package/IceTestCase.class/instance/testListBranchesListsNewBranchWithSlashes.st, Iceberg-Tests.package/IceTestDefinition.class/instance/key.st, Iceberg-Tests.package/IceTreeConstructionTests.class/instance/testCreateDirectoryWithPackage.st, Iceberg-Tests.package/IceWithRemoteAndUnknownCommitFixture.class/instance/setUp.st, Iceberg-Tests.package/IceWithRemoteFixture.class/instance/setUp.st
- Categorization
- Remove unused variables
- Remove methods equivalent to their super
- Use #assert:equals: instead of #assert: and #=
=> Correct some lints in tests.

README.md, appveyor.yml
I do not know why the Pharo7.0 job is failing but the 6.1 succeeded to complete:
https://ci.appveyor.com/project/VincentBlondeau/iceberg
I think you still have to activate the pharo-vcs project on appveyor
=> Add Windows ci with Appveyor

Iceberg-TipUI.package/IceTipAddPackagesDialog.class/instance/allPackagesNotRegistered.st, Iceberg-TipUI.package/IceTipAddPackagesDialog.class/instance/initializeDialogWindow..st, Iceberg-TipUI.package/IceTipAddPackagesDialog.class/instance/newPackagesListDataSource.st, Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/packages.st, Iceberg-TipUI.package/IceTipSelectingDataSource.class/README.md, Iceberg-TipUI.package/IceTipSelectingDataSource.class/instance/add..st, Iceberg-TipUI.package/IceTipSelectingDataSource.class/instance/onSelectionChangedBlock..st, Iceberg-TipUI.package/IceTipSelectingDataSource.class/instance/onSelectionChangedBlock.st, Iceberg-TipUI.package/IceTipSelectingDataSource.class/instance/remove..st, Iceberg-TipUI.package/IceTipSelectingDataSource.class/instance/toggleSelectionOf..st, Iceberg-TipUI.package/IceTipSelectingDataSource.class/properties.json
- Exclude packages already in the repository
- Disable accept button when no item is selected
- Rename "ok" button to "Add"
Fixes https://github.com/pharo-vcs/iceberg/issues/827
=> Improve add packages dialog

Iceberg-TipUI.package/IceTipEditProjectDialog.class/instance/initializeWidgets.st
Fix #951
Rename directory label into "code directory" in the project edition dialog.
=> Rename directory label into "code directory"

Iceberg-Plugin-GitHub.package/IceHttpsProtocol.extension/class/githubRequestUrlKey.st, Iceberg-Plugin-GitHub.package/IceHttpsProtocol.extension/properties.json, Iceberg-Plugin-GitHub.package/IceSSHProtocol.extension/class/githubRequestUrlKey.st, Iceberg-Plugin-GitHub.package/IceSSHProtocol.extension/properties.json, Iceberg-Plugin-GitHub.package/IceTipGitHubRepositoryPanel.class/instance/getGitHubRepository.st, Iceberg-Plugin-GitHub.package/IceTipGitHubRepositoryPanel.class/instance/newRepository.st, Iceberg-Plugin-GitHub.package/IceUrlProtocol.extension/class/githubRequestUrlKey.st, Iceberg-Plugin-GitHub.package/IceUrlProtocol.extension/properties.json, Iceberg-TipUI.package/IceTipLocalRepositoryPanel.class/class/title.st, Iceberg-TipUI.package/IceTipLocalRepositoryPanel.class/instance/newRepository.st, Iceberg-TipUI.package/monticello.meta/categories.st
Fix #961
- configure remotes with the same protocol than the clone
- remove useless retry
=> Fix configuration of remotes

Iceberg-Libgit.package/IceLibgitRepository.class/instance/mcVersionFor..st, Iceberg-Plugin-Migration.package/IceConvertFormatAction.class/instance/ensureMCVersionWithClassOrganisation..st, Iceberg-Plugin-Migration.package/IceConvertFormatAction.class/instance/migratePackage.commit..st
ensures a class organisation is always present when converting a package.
Fixes #992
=> 992-fix-tonel-migration

Iceberg-TipUI.package/IceTipCreateTagCommand.class/class/defaultMenuItemName.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/class/defaultSpec.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/class/title.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/existingTagsList.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/initializeCurrentBranchLabel.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/initializeExistingTagsList.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/initializeNextTagPanel.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/initializeWidgetsContents.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/latestTagParts.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/latestTagPartsIn..st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/majorButton.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/minorButton.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/patchButton.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/instance/title.st, Iceberg-TipUI.package/IceTipCreateTagPanel.class/properties.json, Iceberg-UI-Tests.package/IceTipCreateTagPanelTest.class/instance/testLatestTagPartsNoNumeric.st, Iceberg-UI-Tests.package/IceTipCreateTagPanelTest.class/instance/testLatestTagPartsNoNumeric2.st, Iceberg-UI-Tests.package/IceTipCreateTagPanelTest.class/instance/testLatestTagPartsPadded.st, Iceberg-UI-Tests.package/IceTipCreateTagPanelTest.class/instance/testLatestTagPartsWithExtra.st, Iceberg-UI-Tests.package/IceTipCreateTagPanelTest.class/instance/testLatestTagPartsWithPrefix.st, Iceberg-UI-Tests.package/IceTipCreateTagPanelTest.class/instance/testLatestTagPartsWithoutPrefix.st, Iceberg-UI-Tests.package/IceTipCreateTagPanelTest.class/properties.json
Added buttons to create next logical semantic versions and the listing of current tags.
As there is no Semver library for pharo (afaik), the version extraction is freehanded (but I've added tests for that).
=> Improved new tag dialog

Iceberg-Plugin-GitHub.package/IceGitHubNewPullRequestAction.class/instance/basicExecute.st, Iceberg-Plugin-GitHub.package/IceGitHubPullRequestDefinition.class/instance/send.st, Iceberg-Plugin-GitHub.package/MorphicUIManager.extension/instance/inform.actionOnClick..st, Iceberg-Plugin-GitHub.package/MorphicUIManager.extension/properties.json, Iceberg-Plugin-GitHub.package/UIManager.extension/instance/inform.actionOnClick..st, Iceberg-Plugin-GitHub.package/UIManager.extension/properties.json
When creating a PR we now have the possibility to open the PR on GitHub.
Fixes #1044
=> 1044-Show-a-button-View-on-Github-when-creating-a-PR

Iceberg-Plugin-GitHub.package/IceDiff.extension/instance/changes.st, Iceberg-Plugin-GitHub.package/IceDiff.extension/properties.json, Iceberg-Plugin-GitHub.package/IceDiffNode.class/class/on..st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/balloonText.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/browse.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/canBeBrowsed.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/canBrowseReferences.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/children.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/contents.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/description.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/hasContents.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/hasEquivalentIn..st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/highlightingColor.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/icon.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/install.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/key.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/myVersion.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/node..st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/node.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/printOn..st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/instance/theirVersion.st, Iceberg-Plugin-GitHub.package/IceDiffNode.class/properties.json, Iceberg-Plugin-GitHub.package/IceGitHubPullRequestBrowser.class/instance/compose.st, Iceberg-Plugin-GitHub.package/IceGitHubPullRequestBrowser.class/instance/mergeBaseCommitFor..st, Iceberg-Plugin-GitHub.package/IceGitHubPullRequestBrowser.class/instance/mergeBaseFor..st
Restore the PR review tool. Is still in Glamour but at least it works.
Fixes #775
=> 775-Reviewing-a-PR-is-broken

Iceberg-TipUI.package/IceTipBranchModel.class/instance/printOn..st, Iceberg-TipUI.package/IceTipCachedModel.class/instance/printOn..st, Iceberg-TipUI.package/IceTipExistingBranchPanel.class/instance/initializeBranchesList.st, Iceberg-TipUI.package/IceTipExistingBranchPanel.class/instance/validate.st, Iceberg-TipUI.package/IceTipMergeBranchPanel.class/instance/doAccept.st, Iceberg-TipUI.package/IceTipRemoteModel.class/instance/branchModels.st, Iceberg-TipUI.package/IceTipRemoteModel.class/instance/branches.st, Iceberg-TipUI.package/IceTipRemoteModel.class/instance/hasBranches.st, Iceberg-TipUI.package/IceTipRemoteModel.class/properties.json, Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/branchModels.st, Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/branches.st, Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/hasBranches.st, Iceberg-TipUI.package/IceTipRepositoryModel.class/properties.json, Iceberg-TipUI.package/TWithBranchModel.trait/instance/branchModels.st, Iceberg-TipUI.package/TWithBranchModel.trait/instance/branches.st, Iceberg-TipUI.package/TWithBranchModel.trait/instance/defaultBranchSelection.st, Iceberg-TipUI.package/TWithBranchModel.trait/instance/hasBranches.st, Iceberg-TipUI.package/TWithBranchModel.trait/instance/repositoryModel.st, Iceberg-TipUI.package/TWithBranchModel.trait/properties.json, Iceberg.package/IceRemote.class/instance/hasBranches.st
Improve robustess and UX of merge dialog
- Do no throw a MNU if there is no selected branch
- Select a branch by default if there is one present (either the head of the first one)
Fixes #1036
=> 1036-Debugger-if-we-try-to-merge-without-selecting-a-branch

Iceberg-Plugin-GitHub.package/IceGitHubPullRequestDataSource.class/instance/iconForStatus..st, Iceberg-Plugin-GitHub.package/IceGitHubPullRequestDataSource.class/instance/iconNameForStatus..st, Iceberg-Plugin-GitHub.package/IceNewBranchFromGitHubIssueCommand.class/class/defaultMenuIconName.st, Iceberg-Plugin-GitHub.package/IceNewBranchFromGitHubIssueCommand.class/instance/defaultMenuIcon.st, Iceberg-Plugin-Pharo.package/IcePharoMenuGroup.class/instance/icon.st, Iceberg-Plugin-Pharo.package/IceTipNewBranchFromIssueCommand.class/class/defaultMenuIconName.st, Iceberg-Plugin-Pharo.package/IceTipNewBranchFromIssueCommand.class/instance/defaultMenuIcon.st, Iceberg-TipUI.package/IceClassDefinition.extension/instance/icon.st, Iceberg-TipUI.package/IceConflictingOperation.extension/instance/operationIcon.st, Iceberg-TipUI.package/IceDefinition.extension/instance/iconNamed..st, Iceberg-TipUI.package/IceExtensionDefinition.extension/instance/icon.st, Iceberg-TipUI.package/IceOperationMerge.extension/instance/icon.st, Iceberg-TipUI.package/IcePackageDefinition.extension/instance/icon.st, Iceberg-TipUI.package/IceTipAction.class/class/iconNamed..st, Iceberg-TipUI.package/IceTipBrowser.class/instance/iconNamed..st, Iceberg-TipUI.package/IceTipComposablePresenter.class/class/iconNamed..st, Iceberg-TipUI.package/IceTipComposablePresenter.class/instance/iconNamed..st, Iceberg-TipUI.package/IceTraitDefinition.extension/instance/icon.st, Iceberg-TipUI.package/MCAddition.extension/instance/icon.st, Iceberg-TipUI.package/MCModification.extension/instance/icon.st, Iceberg-TipUI.package/MCRemoval.extension/instance/icon.st, Iceberg.package/Iceberg.class/class/settingsOn..st
This PR remove a lot of the usage of Object>>iconNamed: 
It does not remove everything but this is a first pass.
=> 1061-Introduce-iconNamed-in-IceDefinition-and-IceTipModel-and-remove-all-the-terrible-Smalltalk-ui-icons

Iceberg-Libgit.package/IceGitLocalBranch.class/instance/basicPushTo..st, Iceberg-Libgit.package/IceGitLocalBranch.class/instance/pushBranchToRemote.gitRemote.progress..st, Iceberg-Libgit.package/IceGitLocalBranch.class/instance/pushTag.toRemote.gitRemote.progress..st, Iceberg-Libgit.package/IceGitLocalBranch.class/instance/pushTagsToRemote.gitRemote.progress..st, Iceberg-Libgit.package/IceGitLocalBranch.class/instance/pushTo..st, Iceberg-Libgit.package/IceGitLocalBranch.class/instance/setUpstreamIfMissing..st
apparently, this was not merged in the right branch then the change was lost.
=> set upstream if missing

Iceberg.package/IceSystemEventListener.class/class/handleClassChange..st
Fix issue #1106
Correctly ask the announcement for the affected packages and not to the class.
=> 1106-Moving-a-class-between-packages-not-properly-catched

scripts/preLoading.st
Since now commander (and possibly in the future iceberg itself and its dependencies) might be in tonel format, we need to load tonel before attempting to load. 
Follow-up of the original issue in here: https://github.com/pharo-vcs/iceberg/pull/1125
=> Load tonel as pre-load action

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/libGit..st
It requires a new version of LibGit
=> Fixing Issue #1158. Libraries should be loaded  using absolute paths.

Iceberg-Tests/IceMultiplePackageRepositoryTest.class.st, Iceberg-TipUI/IceTipAdoptCommitCommand.class.st, Iceberg-TipUI/IceTipCommitModel.class.st
Add the adopt option in the UI.
This option will set the selected commit as the current working copy commit, without checking out the commit.
=> Add adopt option

Iceberg-TipUI/IceTipHiedraDataSource.class.st, Iceberg-TipUI/IceTipHiedraHistoryBrowser.class.st, Iceberg-TipUI/IceTipRepositoryBrowser.class.st
Add a Hiedra column to the Repository window. 
I adds a delay when the window is opened because it is not asynchronous. But I think the information it adds makes it worth. 
In small branches it was a few milliseconds in my laptop, and the worst case I tested is 500ms slowdown with the dev-1.0 branch of the iceberg repository (>2800 commits).
The rendering part is not significant in performance because it uses a kind of pagination. For example, if a fasttable is opened and only the top 20 rows are visible, only one "page" of 30 rows are rendered and cached initially. When user scrolls the table, more pages of 30 rows are rendered on demand.
What could be optimized yet is the graph model: when the fasttable is opened, Hiedra currently iterates over all the commits and parents to create the …
=> 1217-Introduce-Hiedra-to-repository-browser

Iceberg-Metacello-Integration/IceGitRepositoryType.class.st, Iceberg-Metacello-Integration/IceMetacelloRepositoryType.class.st, Iceberg-Metacello-Integration/IceProviderRepositoryType.class.st, Iceberg-Metacello-Integration/MCGitRemoteRepository.class.st, Iceberg/IceAnnouncer.class.st, Iceberg/IceMCVersionInfo.class.st
this will allow users to declare repositories like this: 
```Smalltalk
Metacello new 
repository: 'git:https://someprivaterepo.com/path/to/project.git';
baseline: 'MyBaseline';
load.
```
or
```Smalltalk
Metacello new 
repository: 'git:git@someprivaterepo.com:path/to/project.git';
baseline: 'MyBaseline';
load.
```
=> Feature: add generic git repository

Iceberg-TipUI/IceTipCommitAction.class.st, Iceberg-TipUI/IceTipPushAction.class.st
Adding the announcing of push and commit on the commands commit/ push. 
It is really simple add of announcement. It does not add tests, since i don't have an implication, is just for articulating other applications. 
Maybe we should discuss on how and why to test the announcements.
=> 1345-The-IcePushed-and-IceCommited-announcement-are-never-announced

Iceberg-TipUI.package/IceTipRemoveRepositoryDialog.class/class/defaultSpec.st
The text was crop on the right.
=> Adapt UI so the text is not cut on the right

Iceberg-Libgit-Filetree/IceLibgitFiletreeLogReader.class.st
IceLibgitFiletreeLogReader>>loadDefinitions set the entryPath relative to the git repository root, not just the package name.
Fixes: https://github.com/pharo-project/pharo/issues/5578
=> 5578-Iceberg-method-history-shows-only-oldest-commit

Iceberg-Plugin-GitHub/IceTokenCredentials.extension.st, Iceberg-TipUI/IceTipAddTokenCredentialCommand.class.st, Iceberg-TipUI/IceTipAddTokenCredentialsModel.class.st, Iceberg-TipUI/IceTipEditTokenCredentialsModel.class.st, Iceberg-TipUI/IceTokenCredentials.extension.st, Iceberg/IceTokenCredentials.class.st
Intends to fix #1392. Should I write something about this new credentials? where?
Following, the steps to test this PR in a **Pharo 9** (there is another issue open for Pharo 8).
First, add a token to the image:
1. In your GitHub account, create a Personal Access Token (Guide: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token)
2. In Pharo, open Iceberg -> Settings -> Edit credentials -> +Token, as shown in the screenshot below.
Lastly, you can try the token with this adhoc test in a Workspace:
~~~Smalltalk
"https://docs.github.com/en/free-pro-team@latest/rest/reference/rate-limit"
rateLimitWithAuthentication := ((IceGitHubAPI new get: 'rate_limit') at: 'rate') at: 'limit'. 
rateLimitWithoutAuthentication := ((IceGitHubAPI new …
=> Support GitHub Personal Access Tokens

Iceberg-Plugin-Pharo/IcePharoPlugin.class.st
the idea is to have 
pharo
pharo-spec2
pharo-newtools 
as predefined projects in pharo.
Maybe we can add also pharo-iceberg?
Maybe I need to do this directly to dev-1.9?
=> add subprojects to Pharo plugin
