.smalltalk.ston
.travis.yml

With this commit you should only need to register your github account to https://travis-ci.org/
Issue: https://github.com/npasserini/iceberg/issues/116

Add travis configurations

---

Iceberg-Tests.package/IceRepositoryTest.class/instance/testLoadCommit.st
Iceberg.package/IceBranch.class/instance/^equals.st
Iceberg.package/IceBranch.class/instance/backend.st
Iceberg.package/IceBranch.class/instance/ownCommits.st
Iceberg.package/IceCommitInfo.class/instance/backend.st
Iceberg.package/IceCommitInfo.class/instance/lookupVersionFor..st
Iceberg.package/IceCommitInfo.class/instance/mergeInto..st
Iceberg.package/IceCommitInfo.class/instance/properVersionFor..st
Iceberg.package/IceCommitInfo.class/instance/versionsChangedSince..st
Iceberg.package/IceGlamourPublishBrowser.class/instance/compose.st
Iceberg.package/IceGlamourPublishBrowser.class/instance/mergeIntoAction.st
Iceberg.package/IceHistoryBrowser.class/instance/composeCommitsIn..st
Iceberg.package/IceHistoryBrowser.class/instance/mergeIntoAction.st
Iceberg.package/IceMCGitRepository.class/instance/allBranchNames.st
Iceberg.package/IceMCGitRepository.class/instance/commitsOnlyIn..st
Iceberg.package/IceMCGitRepository.class/instance/merge.into..st
Iceberg.package/IceRepositoriesBrowser.class/class/statusFor..st
Iceberg.package/IceRepositoriesBrowser.class/instance/composeRepositoriesIn..st
Iceberg.package/IceRepositoriesBrowser.class/instance/createNewBranch.st
Iceberg.package/IceRepositoriesBrowser.class/instance/pushAction.st
Iceberg.package/IceRepository.class/instance/branchesForMerge.st
Iceberg.package/IceRepository.class/instance/outgoingCommits.st
Iceberg.package/IceSavedPackage.class/instance/loadedVersion.st
Iceberg.package/IceSavedPackage.class/instance/versions.st
Iceberg.package/IceTool.class/class/createNewBranchIn..st
Iceberg.package/Iceberg.class/class/update.st
Iceberg.package/MCGitHubRepository.extension/instance/commitId.st
Iceberg.package/MCGitHubRepository.extension/instance/getOrCreateIcebergRepository.st
Iceberg.package/TIceTool.trait/instance/mergeIntoAnotherBranch.andThen..st
Iceberg.package/TIceTool.trait/instance/pushRepository.andThen..st

Includes some simple tools to switch branches, create new branches and merge between them.

Prepublish v0.3 update 2

---

.travis.yml

Fixing some problems with osx.

Fixing ssh key macos

---

Iceberg-UI.package/IceCreateRepositoryModel.class/instance/changeLocation.st

fix changeLocation

---

Iceberg-UI.package/IcePackageModel.class/instance/reload.st
Iceberg-UI.package/IceRepositoriesBrowser.class/instance/composePackagesListIn..st
Iceberg-UI.package/IceRepositoriesBrowser.class/instance/reloadAllPackagesAction.st
Iceberg-UI.package/IceRepositoriesBrowser.class/instance/reloadPackageAction.st
Iceberg.package/IceSavedPackage.class/instance/reload.st

adds option to reload loaded packages from the context menu or all with the "reaload all"

Packages reloading

---

Iceberg.package/Iceberg.class/class/announcer.st
Iceberg.package/Iceberg.class/properties.json

Renamed IcebergAnnouncer -> icebergAnnouncer in class Iceberg

Class instance variable IcebergAnnouncer in Iceberg should start lowercase 

---

Iceberg.package/IceHttpRemote.class/instance/parseUrl.st

rebased pull request from  @theseion URL parsing fix #363 to dev-0.4

Rebased #363 to dev-0.4

---

Iceberg.package/IceLocalBranch.class/properties.json

See: https://github.com/pharo-vcs/iceberg/issues/379

Remove unused variables.

---

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/baseline..st
BaselineOfIceberg.package/BaselineOfIceberg.class/instance/resetKMRepository.st
Iceberg-UI.package/IceRepositoriesBrowser.class/class/menuCommandOn..st
Iceberg-UI.package/PharoShortcuts.extension/instance/openIcebergShortcut.st
Iceberg-UI.package/PharoShortcuts.extension/properties.json
Iceberg-UI.package/ToolShortcutsCategory.extension/instance/openIceberg.st
Iceberg-UI.package/ToolShortcutsCategory.extension/properties.json

Issue related: https://github.com/pharo-vcs/iceberg/issues/390

Add shortcut to open Iceberg. (meta o + meta i).

---

Iceberg-Metacello-Integration.package/IceGitLocalRepositoryType.class/instance/splitRootAndSubdirectoryFromLocation.st

Fixed multilevel submodule directory scanning

Fixed multilevel submodule directory scanning

---

Iceberg.package/IceRepository.class/instance/location..st

force to refresh name when changing locations (maybe an error? we'll see)

fix on IceRepository>>#location: 

---

Iceberg-UI.package/IceCachedValue.class/instance/invalidateOn.from..st
Iceberg-UI.package/IceDiffChangeTreeBuilder.class/instance/buildOn..st
Iceberg-UI.package/IceDiffCherryPickChangeTreeBuilder.class/instance/buildOn..st
Iceberg-UI.package/IceRepositoriesBrowser.class/instance/composeRepositories.in..st
Iceberg-UI.package/IceRepositoriesBrowser.class/instance/composeRepositoriesIn..st
Iceberg.package/IceDiff.class/instance/repository..st

See issue: https://github.com/pharo-vcs/iceberg/issues/443

Change senders of #subscribe:send:to: to use #when:send:to:

---

Iceberg-Plugin-GitHub.package/IceGitHubCreatePullRequestModel.class/instance/initializePresenter.st
Iceberg-Plugin-GitHub.package/IceGitHubCreatePullRequestModel.class/instance/obtainLastCommitMessage.st
Iceberg-Plugin-GitHub.package/monticello.meta/categories.st

getting last commit message as default test for PR
fixes #398

add-default-comment-for-PR

---

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/baseline..st
Iceberg-UI.package/IceRepositoriesBrowser.class/instance/fetchAction.st
Iceberg.package/IceSavedPackage.class/instance/isModified.st

otherwise install on Pharo6.1 fails :(

release 0.6.1

---

Iceberg.package/IceRepository.class/instance/validateCanCommit.st

fixes #526

---

Iceberg-UI.package/IceRepositoriesBrowser.class/class/menuCommandOn..st

Add help to Iceberg world menu entry.
Close #537

Add help to Iceberg world menu entry.

---

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/libGit..st
BaselineOfIceberg.package/BaselineOfIceberg.class/instance/resetKMRepository.st
BaselineOfIceberg.package/BaselineOfIceberg.class/instance/tonel..st
Iceberg-UI.package/IceInteractiveCredentialsProvider.class/class/isDefault.st
Iceberg-UI.package/IceInteractiveCredentialsProvider.class/instance/initialize.st
Iceberg-UI.package/IceInteractiveCredentialsProvider.class/instance/obtainPlaintextCredentials..st
Iceberg-UI.package/IceInteractiveCredentialsProvider.class/instance/obtainSshCredentials..st
Iceberg-UI.package/IceRepositoryModel.class/instance/fetch.st
Iceberg.package/IceCredentialsProvider.class/class/defaultCredentialProviderClass.st
Iceberg.package/IceCredentialsProvider.class/class/isDefault.st
Iceberg.package/IceCredentialsProvider.class/class/providerType..st
Iceberg.package/IceCredentialsProvider.class/class/providerType.st
Iceberg.package/IceCredentialsProvider.class/instance/obtainPlaintextCredentials..st
Iceberg.package/IceCredentialsProvider.class/instance/obtainSshCredentials..st
Iceberg.package/IceCredentialsProvider.class/instance/providePlaintextCredentialsTo..st
Iceberg.package/IceCredentialsProvider.class/instance/provideSshAgentCredentialsTo..st
Iceberg.package/IceCredentialsProvider.class/instance/provideSshCredentialsTo..st
Iceberg.package/IceLoadedCode.class/instance/changedPackagesToWorkingCopy..st
Iceberg.package/IceNonInteractiveCredentialsProvider.class/README.md
Iceberg.package/IceNonInteractiveCredentialsProvider.class/instance/obtainPlaintextCredentials..st
Iceberg.package/IceNonInteractiveCredentialsProvider.class/instance/obtainSshCredentials..st
Iceberg.package/IceNonInteractiveCredentialsProvider.class/properties.json
Iceberg.package/Iceberg.class/class/initialize.st

- #545: iceberg should be able to work on non UI images (enhancement)
- #537: Iceberg world menu entry should have a tooltip explaining what is Iceberg (enhancement)

release 0.6.6

---

Iceberg-Metacello-Integration.package/IceGithubRepositoryType.class/instance/mcRepository.st
Iceberg-Metacello-Integration.package/IceProviderRepositoryType.class/instance/mcRepository.st
Iceberg-Metacello-Integration.package/IceProviderRepositoryType.class/instance/mcRepositoryClass.st

Requires pharo-project/pharo#20953: Gitlab Private Project Support (via Iceberg)

[Enh]: Fixes #558: Gitlab Private Project Support

---

Iceberg-Libgit.package/IceLibgitErrorVisitor.class/instance/visitERROR..st
Iceberg-Libgit.package/IceLibgitErrorVisitor.class/instance/visitEUSER..st

- #577: Metacello integration is broken in 0.6.7 (bug)

release 0.6.8

---

.smalltalk.ston
.travis.yml
Iceberg-Tests.package/IceAbstractTestCase.class/instance/setUp.st
Iceberg-Tests.package/IceMetacelloIntegrationTests.class/instance/tearDown.st
scripts/postLoading.st
scripts/preLoading.st

We need to have green tests if we are going to accept contributions.

Fix Travis CI

---

Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/numberOfOutgoingCommits.st
Iceberg-TipUI.package/IceTipToolbarItemButtonMorph.class/instance/drawBadgeOn..st
Iceberg-TipUI.package/IceTipToolbarItemButtonMorph.class/instance/newBadgeFont.st

Fix for issue #636
- Star badge
- better badge fonts

Add a star badge in the push button in case of a new branch

---

Iceberg-Plugin-GitHub.package/IceGitHubAction.class/instance/reportError..st

Better error reporting on github error

Fix issue #639

---

Iceberg-Libgit.package/IceGitIndex.class/instance/commitWithMessage.andParents..st
Iceberg-Libgit.package/TIceRepositoryReader.trait/properties.json
Iceberg-Libgit.package/TIceRepositoryWriter.trait/properties.json
Iceberg-Tests.package/IceGitCommitMessage.class/instance/newFixture.st
Iceberg-Tests.package/IceGitCommitMessage.class/instance/testCommitEmptyString.st
Iceberg-Tests.package/IceGitCommitMessage.class/instance/testCommitNullString.st
Iceberg-Tests.package/IceGitCommitMessage.class/instance/testCommitWithEndingPesosSign.st
Iceberg-Tests.package/IceGitCommitMessage.class/instance/testCommitWithoutPesosSign.st
Iceberg-Tests.package/IceGitCommitMessage.class/instance/testDifferentSizes.st
Iceberg-Tests.package/IceGitCommitMessage.class/properties.json

There was a problem when we were passing a byteArray instead of an String in the FFI call.

Fixes #666

---

Iceberg.package/IceSystemEventListener.class/class/handleVersionLoaded..st

diff calculation is creating problems on the installation on Pharo

Patch diff calculation on unknown commit

---

Iceberg.package/IceSystemEventListener.class/class/handleVersionLoaded..st

It happens when the package does not exists

Fixing a problem when the Announced package is nil

---

Iceberg-Plugin-Pharo.package/IcePharoPlugin.class/instance/repositoryWillBeCreated..st

Fixes https://github.com/pharo-vcs/iceberg/issues/619

IcePharoPlugin should not care of Pharo 6 since it'll just bug.

---

Iceberg-Libgit.package/IceRepositoryProperties.class/class/fromCommitish..st
Iceberg-Libgit.package/IceRepositoryProperties.class/class/readPropertiesFrom..st

Fixes https://github.com/pharo-vcs/iceberg/issues/669
PLEASE REVIEW! Since I'm not that familiar with the streams maybe there is a better solution.
Also, It would be cool if it could make it for release v0.7.4 because I'm stuck with Iceberg v0.7.2 to work on my projects.

Adapt properties reading of Tonel projects for Pharo 6.1.

---

.travis.yml

Update .travis.yml to test Pharo 6 and 64 bits

---

Iceberg-Libgit.package/IceGitCommit.class/instance/fetchPackageNames.st
Iceberg-Libgit.package/IceLibgitRepository.class/instance/createSourceDirectory.st
Iceberg-TipUI.package/IceTipContext.class/instance/isRepositoryMissing.st
Iceberg-TipUI.package/IceTipRepairCreateSubdirectory.class/README.md
Iceberg-TipUI.package/IceTipRepairCreateSubdirectory.class/class/help.st
Iceberg-TipUI.package/IceTipRepairCreateSubdirectory.class/class/icon.st
Iceberg-TipUI.package/IceTipRepairCreateSubdirectory.class/class/isAvailableFor..st
Iceberg-TipUI.package/IceTipRepairCreateSubdirectory.class/class/order.st
Iceberg-TipUI.package/IceTipRepairCreateSubdirectory.class/class/title.st
Iceberg-TipUI.package/IceTipRepairCreateSubdirectory.class/instance/basicExecute.st
Iceberg-TipUI.package/IceTipRepairCreateSubdirectory.class/properties.json
Iceberg-TipUI.package/IceTipRepairEditRepository.class/README.md
Iceberg-TipUI.package/IceTipRepairEditRepository.class/class/help.st
Iceberg-TipUI.package/IceTipRepairEditRepository.class/class/icon.st
Iceberg-TipUI.package/IceTipRepairEditRepository.class/class/isAvailableFor..st
Iceberg-TipUI.package/IceTipRepairEditRepository.class/class/order.st
Iceberg-TipUI.package/IceTipRepairEditRepository.class/class/title.st
Iceberg-TipUI.package/IceTipRepairEditRepository.class/instance/basicExecute.st
Iceberg-TipUI.package/IceTipRepairEditRepository.class/properties.json
Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/createSourceDirectory.st
Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/isCodeMissing.st
Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/longStatus.st
Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/updateLocation.subdirectory..st

Adding repair actions to the code subdirectory missing problem.
Fixes #748

Adding repair actions to the code subdirectory missing problem.

---

Iceberg-Pharo6.package/StringMorph.extension/instance/addEmphasis..st
Iceberg-Pharo6.package/StringMorph.extension/properties.json
Iceberg-Pharo6.package/TextEmphasis.extension/instance/value.st
Iceberg-Pharo6.package/TextEmphasis.extension/properties.json

Fixes https://github.com/pharo-vcs/iceberg/issues/756

Add compatibility methods for Pharo 6.1

---

Iceberg-Plugin-GitHub.package/IceGitHubPullRequestDataSource.class/instance/copyToClipboard..st
Iceberg-TipUI.package/Clipboard.extension/class/clipboardText.informing..st
Iceberg-TipUI.package/Clipboard.extension/properties.json
Iceberg-TipUI.package/IceTipCommitModel.class/instance/id.st
Iceberg-TipUI.package/IceTipCommitModel.class/instance/info.st
Iceberg-TipUI.package/IceTipCopyCommitSHACommand.class/class/browserHistoryContextActivation.st
Iceberg-TipUI.package/IceTipCopyCommitSHACommand.class/class/defaultMenuIconName.st
Iceberg-TipUI.package/IceTipCopyCommitSHACommand.class/class/defaultMenuItemName.st
Iceberg-TipUI.package/IceTipCopyCommitSHACommand.class/instance/execute.st
Iceberg-TipUI.package/IceTipCopyCommitSHACommand.class/instance/readParametersFromContext..st
Iceberg-TipUI.package/IceTipCopyCommitSHACommand.class/properties.json
Iceberg-TipUI.package/IceTipRepositoryModel.class/instance/copyCommitIDToClipboard.st
Iceberg-TipUI.package/IceTipRepositoryModel.class/properties.json
Iceberg-TipUI.package/TIceCopyCommitId.trait/README.md
Iceberg-TipUI.package/TIceCopyCommitId.trait/instance/copyToClipboardId..st
Iceberg-TipUI.package/TIceCopyCommitId.trait/properties.json

Fixes https://github.com/pharo-vcs/iceberg/issues/765

Add copy SHA command to history window.

---

.travis.yml
BaselineOfIceberg.package/BaselineOfIceberg.class/instance/osSubprocess..st

Try latest commit of ossubprocess. WIP for #761

Make tests work on 64 bits

---

README.md

This PR proposes some typo and grammar fixes for the README. I tried my best not to reword anything and stick to the source text as much as possible while introducing a few gentle nudges that help improve readability.
Any feedback is welcome!
Cheers

Typo and grammar fixes in README

---

Iceberg.package/IceLogVersion.class/instance/tagNames.st
Iceberg.package/IceLogVersion.class/instance/tags.st

Add missing methods. Fixes https://github.com/pharo-vcs/iceberg/issues/854

addMissingMethods

---

Iceberg-Tests.package/IceCredentialStoreTest.class/instance/tearDown.st
Iceberg-Tests.package/IceCredentialStoreTest.class/instance/testDeprecatedAPI.st
Iceberg-Tests.package/IceCredentialStoreTest.class/instance/testDeprecatedGetterAPI.st
Iceberg-Tests.package/IceCredentialStoreTest.class/instance/testStoreInNonExistingDirectory.st
Iceberg-Tests.package/IceCredentialStoreTest.class/instance/testStoreInNonExistingFile.st
Iceberg-Tests.package/IceCredentialStoreTest.class/properties.json
Iceberg.package/IceCredentialsProvider.class/class/plaintextCredentials..st
Iceberg.package/IceCredentialsProvider.class/class/plaintextCredentials.st

Adding deprecation of old CredentialProvider class API, and adding tests.

CredentialStore API

---

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/tonel..st

update tonel to v1.0.9

---

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/commander..st

new Commander with deprecated renamed classes

useCommander063

---

Iceberg-TipUI.package/IceTipEditProjectDialog.class/class/defaultSpec.st
Iceberg-TipUI.package/IceTipEditProjectDialog.class/instance/initialExtent.st
Iceberg-TipUI.package/IceTipEditProjectDialog.class/instance/initializeDirectoryTree.st
Iceberg-TipUI.package/IceTipEditProjectDialog.class/instance/initializePresenter.st
Iceberg-TipUI.package/IceTipEditProjectDialog.class/instance/initializeWidgets.st
Iceberg-TipUI.package/IceTipEditProjectDialog.class/instance/useSourceFolder.st
Iceberg-TipUI.package/IceTipEditProjectDialog.class/properties.json

Improving the edit project dialog.

---

Iceberg-Plugin-Metacello.package/IceTipMetacelloInstallBaselineCommand.class/instance/basicInstallBaseline.groups..st

Fixing the installation of baselines.

fixingInstallationOfBaselines

---

Iceberg-Libgit.package/IceRepositoryCreator.class/instance/doEnsureProject.st

Fixing tests

---

Iceberg-Metacello-Integration.package/IceGitLocalRepositoryType.class/instance/mcRepository.st

fix-gitlocal-without-project

---

README.md

There was a mix between two questions.

Fix the FAQ

---

Iceberg-Libgit.package/IceRepositoryCreator.class/instance/createNewRepositoryNamed..st
Iceberg-Tests.package/IceSinglePackageLocalGitRepositoryWithComplexSubdirectoryTest.class/instance/newFixture.st
Iceberg-Tests.package/IceSinglePackageLocalGitRepositoryWithComplexSubdirectoryTest.class/properties.json
Iceberg-Tests.package/IceTreeTests.class/instance/testDetectFoundElement.st
Iceberg-Tests.package/IceTreeTests.class/instance/testDetectNotFoundElement.st
Iceberg.package/IceDiff.class/instance/isCodeSubdirectory..st
Iceberg.package/IceNode.class/instance/firstNodeSuchThat.ifNone..st

Fix #965
- manage complex subdirectories (multiple nested directories, directories with dashes)
- manage the case where the subdirectory does not exist
Added tests for both.

Fixes for subdirectory resolution

---

Iceberg-TipUI.package/IceTipLocalRepositoryPanel.class/class/title.st
Iceberg-TipUI.package/IceTipLocalRepositoryPanel.class/instance/newRepository.st
Iceberg-TipUI.package/monticello.meta/categories.st

Fix #964
- more explicit title and progress bar for importing local repositories

Better name for "Add local repository"

---

Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/README.md
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/instance/choosen..st
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/instance/choosen.st
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/instance/isChoiceBetween.and..st
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/instance/optionA..st
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/instance/optionA.st
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/instance/optionB..st
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/instance/optionB.st
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/instance/projectName..st
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/instance/projectName.st
Iceberg-Metacello-Integration.package/IceMetacelloLoadChoice.class/properties.json
Iceberg-Metacello-Integration.package/IceMetacelloLoadSession.class/README.md
Iceberg-Metacello-Integration.package/IceMetacelloLoadSession.class/instance/initialize.st
Iceberg-Metacello-Integration.package/IceMetacelloLoadSession.class/instance/recordChoice..st
Iceberg-Metacello-Integration.package/IceMetacelloLoadSession.class/instance/recordChoiceProject.optionA.optionB.ifAbsentAnswer..st
Iceberg-Metacello-Integration.package/IceMetacelloLoadSession.class/properties.json
Iceberg-Metacello-Integration.package/IceMetacelloLoadSessionContext.class/README.md
Iceberg-Metacello-Integration.package/IceMetacelloLoadSessionContext.class/properties.json
Iceberg-Metacello-Integration.package/IceMetacelloPharoPlatform.class/instance/withMetacelloLoadSessionDo..st
Iceberg-Metacello-Integration.package/MetacelloPlatform.extension/instance/withMetacelloLoadSessionDo..st
Iceberg-Metacello-Integration.package/MetacelloPlatform.extension/properties.json
Iceberg-Metacello-Integration.package/MetacelloScriptApiExecutor.extension/instance/execute..st
Iceberg-Metacello-Integration.package/MetacelloScriptApiExecutor.extension/properties.json
Iceberg-Plugin-Metacello.package/IceTipMetacelloInstallBaselineCommand.class/instance/chooseConflictPolicyFor..st
Iceberg-Plugin-Metacello.package/IceTipMetacelloInstallBaselineCommand.class/instance/chooseConflictPolicyProject.optionA.optionB..st
Iceberg-Plugin-Metacello.package/IceTipMetacelloInstallBaselineCommand.class/instance/chooseUpgradePolicyFor..st
Iceberg-Plugin-Metacello.package/IceTipMetacelloInstallBaselineCommand.class/instance/chooseUpgradePolicyProject.optionA.optionB..st
Iceberg-Plugin-Pharo.package/IcePharoPlugin.class/instance/fetchIfNeeded..st

fix-ask-everytime-conflicting-versions

---

Iceberg-Plugin-GitHub.package/IceCommitInfoModel.class/properties.json
Iceberg-Plugin-GitHub.package/IceGitHubSelectListModel.class/instance/initializeWidgets.st

Remove use of Spec deprecated classes
Fixes #1018

1018-doNotUseDeprecatedClasses

---

Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubAction.class/README.md
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubAction.class/class/organisation.projectName..st
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubAction.class/instance/basicExecute.st
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubAction.class/instance/organisation..st
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubAction.class/instance/organisation.st
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubAction.class/instance/projectName..st
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubAction.class/instance/projectName.st
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubAction.class/properties.json
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubCommand.class/README.md
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubCommand.class/class/browserRepositoryListActivation.st
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubCommand.class/instance/execute.st
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubCommand.class/instance/itemNameWithoutBranches.st
Iceberg-Plugin-GitHub.package/IceGitHubOpenOnGithubCommand.class/properties.json
Iceberg-Plugin-GitHub.package/IceGitHubTreeOpenOnGithubCommand.class/README.md
Iceberg-Plugin-GitHub.package/IceGitHubTreeOpenOnGithubCommand.class/instance/defaultMenuItemName.st
Iceberg-Plugin-GitHub.package/IceGitHubTreeOpenOnGithubCommand.class/instance/execute.st
Iceberg-Plugin-GitHub.package/IceGitHubTreeOpenOnGithubCommand.class/properties.json

Add commands to open remotes on Github directly.
Fixes #1048

1048-Add-a-GitHub-option-open-on-github

---

Iceberg-Libgit.package/IceLibgitRepository.class/instance/branchNamed.ifPresent.ifAbsent..st
Iceberg-Tests.package/IceRepositoryWithSingleRemoteTest.class/instance/testLocalCheckedOutBranchIsEqualsToHEAD.st
Iceberg.package/IceBranch.class/instance/^equals.st
Iceberg.package/IceBranch.class/instance/hash.st
Iceberg.package/IceLocalBranch.class/instance/^equals.st
Iceberg.package/IceLocalBranch.class/instance/hash.st

Fix issue #1104 with tests: bug in fetching branches

1104-pushTo-leads-to-error-on-some-branches

---

Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/README.md
Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/class/actsOnTag..st
Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/class/browserContextActivation.st
Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/class/canBeExecutedInContext..st
Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/class/defaultHelp.st
Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/class/defaultMenuIconName.st
Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/class/defaultMenuItemName.st
Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/instance/execute.st
Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/instance/readParametersFromContext..st
Iceberg-TipUI.package/IceTipCheckoutSelectedTagCommand.class/properties.json
Iceberg-TipUI.package/IceTipTagModel.class/instance/previewCheckout.st
Iceberg.package/IceTag.class/instance/fileSystem.st
Iceberg.package/IceTag.class/instance/gitRef.st
Iceberg.package/IceTag.class/instance/printOn..st

Add command + UI menu to checkout a tag (from the repository view)

1074-cannot-checkout-a-tag

---

Iceberg-TipUI.package/IceTipRemoteActionModel.class/instance/remote.st
Iceberg.package/IceBranch.class/instance/isHead.st

Fix for issue #1105: Be able to create branches in detached HEAD mode

1105-Entering-an-issue-in-create-a-branch-raises-a-DNU

---

BaselineOfIceberg.package/BaselineOfIceberg.class/instance/commander..st

1134-should-depends-on-Commander-0-7-2

---

README.md
scripts/updateIceberg.st

Updating the update instructions

---

Iceberg-Tests/IceMultiplePackageRepositoryTest.class.st
Iceberg-TipUI/IceTipBranchModel.class.st
Iceberg-TipUI/IceTipHistoryContext.class.st
Iceberg-TipUI/IceTipResetBranchToThisCommitCommand.class.st
Iceberg/IceLocalBranch.class.st

Fix #1174
Add Reset command + backend code with tests

1174-Feature-Reset

---

Iceberg-Libgit/IceLibgitTreeBuilder.class.st
Iceberg-Memory/IceMemoryCommitWalk.class.st
Iceberg-Metacello-Integration/IceMetacelloLoadSession.class.st
Iceberg-Plugin-GitHub/IceGitHubAPI.class.st
Iceberg-Plugin-GitHub/IceGitHubAction.class.st
Iceberg-TipUI/IceTipDiffSelectingPanel.class.st
Iceberg-TipUI/IceTipDirectoryDataSource.class.st
Iceberg/IceBasicProject.class.st
Iceberg/IceGitTransferProgress.class.st
Iceberg/IcePackage.class.st
Iceberg/IcePushTransferProgress.class.st

1169-Cleaning-initialization-protocol

---

Iceberg-TipUI/IceTipRepositoriesBrowser.class.st

Closes #1188
Rearrange columns

1188-The-repository-branch-column-is-always-too-small-and-possibly-should-be-3rd-column

---

Iceberg-Libgit.package/IceLibgitCommitWalk.class/instance/hasNext.st
Iceberg-Libgit.package/IceLibgitCommitWalk.class/instance/next.st

Adds next / hasNext on IceLibgitCommitWalk for exposing the revwalk hasNext / next messages

Adds two silly messages

---

README.md

You should still check if the link is the resource that you wanted to link to, in case i misunderstood. 
The previous link is dead anyway.
Pierre.

update tutorial link in README

---

BaselineOfIceberg/BaselineOfIceberg.class.st

tonel-1.0.14

---

Iceberg-Plugin-Migration/IceTipFiletreeToTonelDialog.class.st
Iceberg-TipUI/IceTipAbstractAskCredentialsModel.class.st
Iceberg-TipUI/IceTipAbstractPlaintextCredentialsModel.class.st
Iceberg-TipUI/IceTipAbstractSSHCredentialsModel.class.st
Iceberg-TipUI/IceTipAddPackagesDialog.class.st
Iceberg-TipUI/IceTipAddPlaintextCredentialsModel.class.st
Iceberg-TipUI/IceTipAddRemoteDialog.class.st
Iceberg-TipUI/IceTipAddSSHCredentialsModel.class.st
Iceberg-TipUI/IceTipAskForPlaintextCredentialsModel.class.st
Iceberg-TipUI/IceTipCheckoutBranchDialog.class.st
Iceberg-TipUI/IceTipCredentialsStoreBrowser.class.st
Iceberg-TipUI/IceTipDialog.class.st
Iceberg-TipUI/IceTipEditPlaintextCredentialsModel.class.st
Iceberg-TipUI/IceTipEditSSHCredentialsModel.class.st
Iceberg-TipUI/IceTipErrorDialog.class.st
Iceberg-TipUI/IceTipGitUsernameAndEmailDialog.class.st
Iceberg-TipUI/IceTipInteractiveCredentialsProvider.class.st
Iceberg-TipUI/IceTipLocationPresenter.class.st
Iceberg-TipUI/IceTipOptionDialog.class.st
Iceberg-TipUI/IceTipRemovePackageDialog.class.st
Iceberg-TipUI/IceTipRemoveRepositoryDialog.class.st
Iceberg-TipUI/IceTipRepairRepositoryDialog.class.st
Iceberg-TipUI/IceTipRepositoriesBrowser.class.st
Iceberg-TipUI/IceTipRepositoryBrowser.class.st
Iceberg-TipUI/IceTipWorkingCopyBrowser.class.st

Migration of all windows derivated from IceTipDialog from spec1 to spec 2

Migration of Ice tip dialog to spec2

---

Iceberg-Libgit/IceLibgitRepository.class.st
Iceberg-Libgit/IceRepositoryCreator.class.st
Iceberg-Tests/IceClonedFromRemoteFixture.class.st
Iceberg-Tests/IceGitTestFactory.class.st
Iceberg-Tests/IceWithRemoteAndLocalCommitAndUpstreamFixture.class.st
Iceberg-TipUI/IceTipCommentPanel.class.st
Iceberg-TipUI/IceTipCommitBrowser.class.st
Iceberg-TipUI/IceTipDiffPanel.class.st
Iceberg-TipUI/IceTipSaveImageAction.class.st
Iceberg-UI-Tests/IceTipCommitBrowserTest.class.st
Iceberg-UI-Tests/IceTipCommitBrowserTestWithRemoteSet.class.st
Iceberg-UI-Tests/IceTipCommitBrowserTestWithoutRemoteSet.class.st
Iceberg-UI-Tests/IceTipHistoryBrowserTest.class.st
Iceberg-UI-Tests/IceTipMockSaveImageAction.class.st
Iceberg/IceTipCommitSettings.class.st

The values are stored in Iceberg settings.

Allows to automatically save and push from commit browser

---

Iceberg-TipUI/IceTipRepairRepositoryDialog.class.st

Make spPresenter in repair window not editable.

---

Iceberg-Memory/IceRingWorkingCopyChangerVisitor.class.st
Iceberg-Tests/IceCherryPickingInitialDependencies.class.st
Iceberg-Tests/IceClassesCherryPickingTest.class.st
Iceberg-Tests/IceExtensionMethodCherryPickingTest.class.st
Iceberg-Tests/IceMetaClassCherryPickingTest.class.st
Iceberg-Tests/IceMethodCherryPickingTest.class.st
Iceberg-Tests/IceTraitsCherryPickingTest.class.st
Iceberg-TipUI/IceTipCherryPickCommand.class.st
Iceberg-TipUI/IceTipHistoryBrowser.class.st
Iceberg-TipUI/IceTipRepositoryBrowser.class.st
Iceberg/IceAsDependencyVisitor.class.st
Iceberg/IceCherrypicker.class.st
Iceberg/IceCherrypickerDiffPruner.class.st
Iceberg/IceCherrypickerInitialDependenciesCollector.class.st
Iceberg/IceClassDependency.class.st
Iceberg/IceDefinedDependency.class.st
Iceberg/IceDependency.class.st
Iceberg/IceDependencyEnvironment.class.st
Iceberg/IceExtendedClassDependency.class.st
Iceberg/IceExtensionDefinition.class.st
Iceberg/IceMCDefinitionImporter.class.st
Iceberg/IceMetaclassDependency.class.st
Iceberg/IceMethodDependency.class.st
Iceberg/IceNodeQuery.class.st
Iceberg/IceOperation.class.st
Iceberg/IcePackageDependency.class.st
Iceberg/IceTraitDefinition.class.st
Iceberg/IceTraitDependency.class.st
Iceberg/MCClassTraitDefinition.extension.st

The smart cherry picking is an experimental feature now available by a context menu on commits in the repository browser.

Integrating the smart cherry picking feature to Iceberg

---

Iceberg-TipUI/IceTipRepositoriesBrowser.class.st

Fix repositories browser update

---

Iceberg-Libgit/IceLibgitRepository.class.st
Iceberg-TipUI/FTTableMorph.extension.st
Iceberg-TipUI/IceTipEditProjectDialog.class.st
Iceberg-TipUI/IceTipExistingBranchPanel.class.st
Iceberg/IceCredentialStore.class.st
Iceberg/IceCredentialsProvider.class.st
Iceberg/Iceberg.class.st

This is needed to not have the values of default settings.

Fixing the default values for the settings.

---

BaselineOfIceberg/BaselineOfIceberg.class.st
Iceberg-Tests/IceSinglePackageLocalRepositoryTest.class.st
Iceberg-Tests/RG2MetaclassTraitDefinition.extension.st
Iceberg-Tests/RG2PackageDefinition.extension.st
Iceberg-Tests/RG2TraitDefinition.extension.st
Iceberg/IceTraitDefinition.class.st

- Fixes https://github.com/pharo-project/pharo/issues/5988
- Fixes https://github.com/pharo-vcs/tonel/issues/66

Fixing saving of class traits

---

Iceberg-TipUI/IceTipRepositoryModel.class.st

Fix typo in IceTipRepositoryModel.class.st

---

Iceberg-TipUI/IceTipHistoryBrowser.class.st
Iceberg-TipUI/IceTipRepositoryBrowser.class.st

Auto deprecation magic business

---

docs/Adopt-a-commit-feature.md

[doc] add adopt a commit doc from a mailling list answer

---

Iceberg-Plugin-Pharo/IcePharoPlugin.class.st

dev-1.9 version of https://github.com/pharo-vcs/iceberg/pull/1399

add subprojects to Pharo plugin

---

BaselineOfIceberg/BaselineOfIceberg.class.st

dev-1.9 version of https://github.com/pharo-vcs/iceberg/pull/1401

update to use libgit 2.1.1
